#!/usr/bin/env python

import sys
import pathlib
import numpy as np
from osgeo import gdal

if __name__=='__main__':
    assert len(sys.argv) > 1, 'Need to supply a file'
    filename = pathlib.Path(sys.argv[1])

    tif_file = gdal.Open(str(filename))
    assert tif_file is not None, f'Could not open file {filename}'
    tif_data = tif_file.ReadAsArray()
    unique_labels = np.unique(tif_data)
    print(np.any(np.isnan(tif_data)), tif_data.min(), tif_data.max(), tif_data.shape, unique_labels)

    label_bins = range(max(unique_labels)+1)
    (vals, bins) = np.histogram(tif_data, bins=label_bins)
    val_str = ','.join([str(v) for v in vals])
    print(f'np.array([{val_str}])')


